### ISSUE TITLE
Support Canonical Path Resolution?

### ISSUE THREAD

**Issue by indolering** [PolymerLabs/polybuild#12]
I've got the latest version of seed-element (1.0.4) and PolyBuild (1.0.5) but I am getting errors relating to the canonical path URL system.  Polyserve resolves these canonical path URLs without a problem, am I doing something wrong or does Polyserve not support canonical paths?  If not, how do I (programmatically) build an element that uses canonical paths?

Canonical path URL in `seed-element.html`:

```
<link rel="import" href="../polymer/polymer.html">
```

Output from Polybuild:

```
$ polybuild seed-element.html
ERROR finding /Users/username/parent-dir/polymer/polymer.html
[13:17:08] Error in plugin 'gulp-vulcanize'
Message:
    ENOENT: no such file or directory, open '/Users/username/parent-dir/polymer/polymer.html'
Details:
    errno: -2
    code: ENOENT
    syscall: open
    path: /Users/username/parent-dir/polymer/polymer.html
    fileName: /Users/username/parent-dir/seed-element/seed-element.html
```

**Comment by indolering** [comment]
This is blocking me from using Polybuild, any progress?

**Comment by indolering** [comment]
Workaround: symlink your element into bower_components.  Still confusing, should be documented somewhere....

**Comment by rsDev63** [comment]
Has anyone found another work around for this. I tried using the symlink trick but was unable to successfully do that. I would like to implement a more stable solution as well. I know that Polyserve is supposed to automatically map your projects for you, however, after doing a clean Yoeman polymer seed-generator, Polyserve does not resolve the canonical paths built into the project. I deleted the project, and tried the Polymer guide several times, still without success. I had to hard code the 'app/bower_components' path rather than canonical paths for the project to work.  I appreciate @robdodson 's Polycast videos, which explain the importance of using canonical paths for a flexible build/packaging. I still cannot find a solution.  If anyone has tips on how to make these canonical paths work, or at least can confirm that they also have this issue, I would appreciate it.

**Comment by robdodson** [comment]
cc @justinfagnani

**Comment by rsDev63** [comment]
Thank you @robdodson, and @justinfagnani . I am excited for the reply.

**Comment by montrealist** [comment]
Wondering if there's been any progress on this at all since May?

**Comment by indolering** [comment]
I'm not a fan of polluting comment threads with update requests, but this is a pretty big UX issue.  Is there some high-level plan that we aren't aware of?  Any discussion?  Or should we all stop complaining and start making pull requests?

**Comment by justinfagnani** [comment]
The fundamental issue here is that the `build` command is not intended for individual reusable elements - since, as of the advent of the CLI, they shouldn't be built separate from an application. This means that `build` doesn't support resolving URLs that escape the project folder.

`build` is primarily concerned with bundling, service worker generation, and prefetch hoisting. These things are applicable to reusable elements. The optimization aspects could be, but we think it's a good idea to apply optimizations when building the application too.

I think we need to have much better UX around detecting application-style vs element-style projects and giving good feedback here. We should also open a more general issue about what `build` should do for element projects.

Sorry for the silence here.

**Comment by justinfagnani** [comment]
Whoops! I just realized this issue is on the `polybuild` library and not `polymer-build`. I supposed we should have moved this repo rather than create a new one, but this repo is deprecated in favor of https://github.com/Polymer/polymer-build

The same reasoning applies.

**Comment by indolering** [comment]
> The fundamental issue here is that the build command is not intended for individual reusable elements - since, as of the advent of the CLI, they shouldn't be built separate from an application.

Does the CLI offer an alternative?  Sorry, I've been out of the Polymer loop for a while : )

> Whoops! I just realized this issue is on the polybuild library and not polymer-build.

Let's move the party there! https://github.com/Polymer/polymer-build/issues/59
